// Do not edit. Generated by misc/build-tslibs.js
export const dom = {
  filename: "lib.dom.d.ts",
  version: "+EviNZmp2POY3vxI1MwvwLsktEk"
};
export const webworker = {
  filename: "lib.webworker.d.ts",
  version: "nkpjZop6oiU0iz4a83cmigz6edo"
};
export const scripter = {
  filename: "scripter-env.d.ts",
  version: "kjcArpj2HwgBI7x+YfnnohdvGBU"
};
export const figma = {
  filename: "figma.d.ts",
  version: "MV8+GqT9BiKjnffdIoty94fCZBE"
};
