// Do not edit. Generated by misc/build-tslibs.js
export const dom = {
  filename: "lib.dom.d.ts",
  version: "+EviNZmp2POY3vxI1MwvwLsktEk"
};
export const webworker = {
  filename: "lib.webworker.d.ts",
  version: "6NuArQ9ZIk+1Rs0FkMNjr1RlEp4"
};
export const scripter = {
  filename: "scripter-env.d.ts",
  version: "CjTzwTYb5gIj8RLHaJBddhtIH+A"
};
export const figma = {
  filename: "figma.d.ts",
  version: "MV8+GqT9BiKjnffdIoty94fCZBE"
};
